server:
  port: 8080

spring:
  application:
    name: no-bookkeeping
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url:
      username:
      password:

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tkzj.entity